### PR TITLE
Added two child classes for the spaceship and the oscillator!

### LINKED ISSUE #3: Implement Spaceship&Oscillator Boards from the main Board blueprint

### PR DESCRIPTION
**Pull request by CedricMurairi**
These classes inherited from the main class Board and defined method each to randomly pick a different spaceship for the ship class or a different oscillator for the oscillator class. Every time the game runs.

### CODE REVIEW

**Review by mtndlovu — CHANGES_REQUESTED** [review]
Kudos for creating boards with special patterns that occur in the Game of Life. However, I don't think that bundling these patterns in one class and then randomly selecting them is a great idea. Rather, it would be better to create the spaceship patterns as classes that inherit from Board. For example:
```
class Glider(Board):
    def __init(self, width, height):
        super().__init__(width, height)
        activate_cells(self, [[2, 5], [3, 5], [4, 5], [4, 4], [3, 3]])
```

Finally, please use `super` when accessing inherited methods. I think it's nicer :)

**Comment by CedricMurairi** [comment]
I have implemented the requested changes

**Review by mtndlovu — COMMENTED** [review]
Ok, that's awesome man. But I would like to request one last change. I suggest that we activate the cells for special boards within the class instead of in the `main` function. Currently, instances of these special boards are just like an ordinary board until we call `activate_cells` in the `main` function.

**Comment by CedricMurairi** [comment]
I have fixed the issue! Did not spot that before 🤔️. It is now happening in the child classes when they are instantiated.

**Comment by CedricMurairi** [comment]
The changes are live now! 😀️

**Review by mtndlovu — APPROVED** [review]

**Pull request merged**
