### PR TITLE
Refactor files

### LINKED ISSUE #5: Refactor the code
Keep one file for classes and the main file for the main program with all the user interactions.

### PR DESCRIPTION
**Pull request by CedricMurairi**
I have created two new files under `life/` and added the main files and fixed import errors. Setup ready for the UI

### CODE REVIEW

**Comment by CedricMurairi** [comment]
I added a `.gitignore` to the `life/` folder

**Review by mtndlovu — CHANGES_REQUESTED** [review]
I am glad you split the code into different files instead of having one huge chunk of code. This will serve us well as we build on this project in the future. However, I have a couple of concerns with some parts of the code:

1. `game_of_life.py`
    -  According to the [PEP8](https://www.python.org/dev/peps/pep-0008/#package-and-module-names) style guide, module names should have **short**, all lowercase names. Underscores can be used to improve readability. In this case, we can keep our module name simple by changing it to `life.py`
    - Boards with pre-built patterns, e.g., `HeavyWeightShip`, activate their cells' initial state when created. I think we can safely remove line 10 `br.activate_cells(board, board.live_cells)`
    - It would be better to put life.py (if you consider changing the name to life.py) inside the life directory
2. Imports
    - The [style guide](https://google.github.io/styleguide/pyguide.html#22-imports) recommends that we use `from x import y as z` if two modules named `y` are to be imported, or `y` is very long. Imports such as `from life import cells as cl` and `from life import boards as br` are therefore in violation of our style guide.
3. It would be better to rename `cells.py` to `cell.py` since it only contains the `Cell` class.
4. It is considered best-practice to put `.gitignore` in the root directory

I think these are some of the issues I picked up. "There is no such thing as perfect code—there is only better code." I am happy to discuss the contents of this review. We can even hop on a call if you need to clarify some parts of this PR.

**Comment by CedricMurairi** [comment]
I am glad you are making these comments. I have not read much from the style guide; it is constructive you pointed it out!
I will implement this feedback as much as I can. Cheers

**Comment by CedricMurairi** [comment]
I will find another name for `game_of_life.py` other than `life.py` since it will cause an error when doing `from life import boards` within `life.py`; confusion between `Folder life/` and `File life.`

**Comment by mtndlovu** [comment]
> I will find another name for `game_of_life.py` other than `life.py` since it will cause an error when doing `from life import boards` within `life.py`; confusion between `Folder life/` and `File life.`

Aah! I had not considered this, but I think using the full module name is an easy fix: `import life.boards` or `from life.cell import Cell`

**Comment by CedricMurairi** [comment]
I have fixed the style and naming of files. All under `life/`, `.gitignore ` under `root/`, `cells.py` to `cell.py`; `import` now better.😃️

**Review by mtndlovu — APPROVED** [review]
Your code made me smile :)

**Pull request merged**
